// ALL modules generated by proto files from  (https://github.com/etcd-io/etcd) v3 API client
pub const XPEER: &'static str = "x-peer";

pub mod authpb;
pub mod etcdserverpb;
pub mod mvccpb;
pub mod v3electionpb;
pub mod v3lockpb;

